### PR TITLE
Fix: Prevent request options mutation.

### LINKED ISSUE #31: Request hooks can mutate request options
### Description
The `request` hook currently merges its results back into the `options` object that was passed into `request`: https://github.com/ExpediaGroup/service-client/blob/df0663054c538b708ef38bfba9ccd980f06ad2a9/lib/hooks.js#L101

Consumers probably aren't expecting their `options` object to be mutated.

### Steps to Reproduce
To reproduce, you'll need a service client plugin that has a `request` hook that returns a field that matches one of the options that was passed into the `request` call. Here's a simple, runnable example: https://repl.it/@seanparmelee/service-client-headers

**Expected behavior:**
The `headers` object that was passed in should not be mutated (i.e. should not contain `marker`)

**Actual behavior:**
The `headers` object was mutated; it contains the `marker` header that was generated by the plugin.

### Versions
2.0.0

### PR DESCRIPTION
**Pull request by ianwhitedeveloper**
## Description
Clone options object in `request` hook to prevent mutation of original options object.

## Motivation and Context
Resolves #31 

## How Has This Been Tested?
Added test to assert desired behavior.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: lib/hooks.js [hunk 1]
```diff
@@ -96,7 +96,7 @@ async function init (options) {
       // for the `request` hook, merge and return options data
       if (hookName === 'request') {
         // merge results of returned hook data
-        const finalData = data.options
+        const finalData = Hoek.clone(data.options)
```
Comment (tuckbick) [inline lib/hooks.js:99]: I feel like blindly cloning the entire object could lead to some poor performance, especially if one of the options is a large object. The possible options included here would be [these](https://github.com/ExpediaGroup/service-client/blob/master/lib/client.js#L110-L121):
```js
let requestOptions = {
    queryParams,
    pathParams,
    baseUrl,
    headers,
    payload,
    redirects,
    timeout,
    connectTimeout,
    maxConnectRetry,
    agent,
    read,
    readOptions
}
```

Most of these could probably easily be cloned, but some of them should be "shallow" copied instead (e.g. `agent`). I'm unsure what should be done with `payload`...

Comment (ianwhitedeveloper) [reply lib/hooks.js:99]: Welp, we could just leave things as-is. The docs do point out that in the request hook data will be merged with the options data so while arguably not expected it is documented: 
> This hook is special. Data returned here will be deep merged with the request options data that will be passed on to Wreck.

Comment (tuckbick) [reply lib/hooks.js:99]: True, it's documented. The side effect still seems odd to me.

How about shallow copying everything except `queryParams`, `pathParams`, and `headers` since those are probably the most typical things that would be modified in a hook? Modifying `payload` or `agent` could get messy.

```suggestion
        const finalData = data.options;
        Object.assign(finalData, {
            queryParams: {...finalData.queryParams},
            pathParams: {...finalData.pathParams},
            headers: {...finalData.headers}
        });
```

The alternative (below) would only shallow copy the big objects that we know about. A user could return _any_ object from a request hook. So picking out specific objects we want to copy in the above example would be better than the one below, imo.

```suggestion
        const finalData = Hoek.clone(data.options, {shallow: ['payload', 'agent']});
```

Comment (ianwhitedeveloper) [reply lib/hooks.js:99]: OK makes sense I was thinking of leveraging that `shallow` option if we were going to move forward with this update. Thanks!

**Comment by tuckbick** [comment]
cc @seanparmelee
